### PR TITLE
Drop ffmpeg dependency.

### PR DESCRIPTION
**Pull request by ekisu**
has a 50% chance of working properly :^)

### CODE REVIEW

**Comment by ekisu** [comment]
It seems mpv is slower to generate thumbnails (around 20% for me, more or less), I thought ffmpeg seeked only to the keyframe (that's why I used hr-seek=no), but that doesn't seems to be the case. Eh, whatever.

**Comment by shinchiro** [comment]
From my benchmark, using mpv directly is more faster than ffmpeg with following args:

```
command.args = {
    "mpv",
    "--msg-level","all=no",
    "--start", "",
    input,
    "--hr-seek=no",
    "--frames","1",
    "--no-audio", "--no-sub",
    "--vf-add=lavfi=[scale=150:-1]",
    "--ovc=rawvideo",
    "--vf-add=lavfi=[format=bgra]",
    "--of", "image2",
    "--no-ometadata",
    "--o=-"
}
```

The only problem I noticed is the cursor showing busy unlike doing with ffmpeg

**Comment by ekisu** [comment]
Yeah, but ffmpeg does precise seeking. I didn't test, but using `-noaccurate_seek` with ffmpeg should make  it faster than mpv again.

**Comment by bun-dev** [comment]
Thanks. I nearly forgot mpv had ffmpeg built in. I'll take convenience(no need for ffmpeg in PATH) over speed. Changes added(Couldn't merge them directly because I applied some other changes first)

**Pull request closed without merging**
